include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/** , /**/*.freezed.dart, /**/*.g.dart ]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    await_only_futures: true
    use_string_buffers: true
    use_build_context_synchronously: true
    avoid_annotating_with_dynamic: true
    avoid_as: true
    always_declare_return_types: true
    prefer_void_to_null: true
    prefer_is_not_empty: true
    prefer_is_empty: true
    prefer_final_parameters: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_relative_imports: true
    prefer_single_quotes: true
