name: code_uml
description: This package help you build UML diagram. You have to copy result from result file and paste in PlantUML
version: 1.0.1
homepage: https://github.com/chashkovdaniil/graph_analyzer/
repository: https://github.com/chashkovdaniil/graph_analyzer/

environment:
  sdk: '>=2.17.0 <4.0.0'

executables: 
  code_uml:

dependencies:
  analyzer: ^5.6.0
  ffi: ^2.0.2
  io: ^1.0.4
#  jni: ^0.5.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0   
#  jnigen: ^0.5.0

topics:
  - analysis                                